---
output:
  pdf_document: default
  html_document: default
---

```{r}
library(tidyverse)
library(lubridate)
```

```{r}
setwd("fitbitdat")
dayact = read_csv("dailyActivity_merged.csv")
daycal = read_csv("dailyCalories_merged.csv")
dayint = read_csv("dailyIntensities_merged.csv")
daystp = read_csv("dailySteps_merged.csv")
```

```{r}
daytotal = cbind(dayact,daycal,dayint,daystp)
```

```{r}
daytotalx = daytotal[!duplicated(as.list(daytotal))]
```

```{r}
names(daytotalx)
```

```{r}
print(cor(daytotalx$VeryActiveDistance,daytotalx$Calories))
print(cor(daytotalx$ModeratelyActiveDistance,daytotalx$Calories))
print(cor(daytotalx$LightActiveDistance,daytotalx$Calories))
print(cor(daytotalx$SedentaryActiveDistance,daytotalx$Calories))
```


```{r}
print(cor(daytotalx$VeryActiveMinutes,daytotalx$Calories))
print(cor(daytotalx$FairlyActiveMinutes,daytotalx$Calories))
print(cor(daytotalx$LightlyActiveMinutes,daytotalx$Calories))
```


```{r}
print(cor(daytotalx$SedentaryMinutes,daytotalx$Calories))
```

```{r}
write_csv(daytotalx,"daily_data_comb.csv")
```

